#!/bin/bash
#SBATCH -D /home/schmidle/code/RL_Race_Game
#SBATCH -J RL_Race_Game
#SBATCH -t 0-01:00:00
#SBATCH --mem-per-cpu=20G
#SBATCH -c 1 #request cpus
# output files
#SBATCH -o /work/schmidle/%j-%x.out

printf "project version: %s" $(git describe --always --dirty --long)
ml purge
ml foss/2022b Python/3.11.2-bare
export PYTHONPATH=/home/schmidle/VirtualEnvs/Rl_Race_Game/lib/python3.11/site-packages:$PYTHONPATH
source /home/schmidle/VirtualEnvs/Rl_Race_Game/bin/activate
python -u /home/schmidle/code/RL_Race_Game/qlearning.py save #load save